export const name = '005_sumber_data'

export async function up(db) {
  await db.query(`DROP TABLE IF EXISTS paket_anggaran`)

  await db.query(`
    CREATE TABLE anggaran_rekap (
      id                   INT AUTO_INCREMENT PRIMARY KEY,
      user_id              INT NOT NULL,
      tahun_id             INT NOT NULL,
      no                   INT,
      tahun_file           INT,
      kode_urusan          VARCHAR(20),
      nama_urusan          VARCHAR(255),
      kode_skpd            VARCHAR(50),
      nama_skpd            VARCHAR(255),
      kode_sub_unit        VARCHAR(50),
      nama_sub_unit        VARCHAR(255),
      kode_bidang_urusan   VARCHAR(20),
      nama_bidang_urusan   VARCHAR(255),
      kode_program         VARCHAR(50),
      nama_program         VARCHAR(255),
      kode_kegiatan        VARCHAR(50),
      nama_kegiatan        VARCHAR(500),
      kode_sub_kegiatan    VARCHAR(50),
      nama_sub_kegiatan    VARCHAR(500),
      kode_sumber_dana     VARCHAR(50),
      nama_sumber_dana     VARCHAR(255),
      kode_rekening        VARCHAR(50),
      nama_rekening        VARCHAR(500),
      paket_kelompok       VARCHAR(50),
      nama_paket_kelompok  VARCHAR(500),
      pagu                 BIGINT DEFAULT 0,
      uploaded_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id)  REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (tahun_id) REFERENCES tahun_anggaran(id) ON DELETE CASCADE
    )
  `)

  await db.query(`
    CREATE TABLE dokumen_realisasi (
      id                       INT AUTO_INCREMENT PRIMARY KEY,
      user_id                  INT NOT NULL,
      tahun_id                 INT NOT NULL,
      kode_skpd                VARCHAR(50),
      nama_skpd                VARCHAR(255),
      kode_sub_skpd            VARCHAR(50),
      nama_sub_skpd            VARCHAR(255),
      kode_fungsi              VARCHAR(20),
      nama_fungsi              VARCHAR(255),
      kode_sub_fungsi          VARCHAR(20),
      nama_sub_fungsi          VARCHAR(255),
      kode_urusan              VARCHAR(20),
      nama_urusan              VARCHAR(255),
      kode_bidang_urusan       VARCHAR(20),
      nama_bidang_urusan       VARCHAR(255),
      kode_program             VARCHAR(50),
      nama_program             VARCHAR(255),
      kode_kegiatan            VARCHAR(50),
      nama_kegiatan            VARCHAR(500),
      kode_sub_kegiatan        VARCHAR(50),
      nama_sub_kegiatan        VARCHAR(500),
      kode_rekening            VARCHAR(50),
      nama_rekening            VARCHAR(500),
      nomor_dokumen            VARCHAR(100),
      jenis_dokumen            VARCHAR(50),
      jenis_transaksi          VARCHAR(50),
      nomor_dpt                VARCHAR(100),
      tanggal_dokumen          VARCHAR(50),
      keterangan_dokumen       TEXT,
      nilai_realisasi          BIGINT DEFAULT 0,
      nilai_setoran            BIGINT DEFAULT 0,
      nip_pegawai              VARCHAR(30),
      nama_pegawai             VARCHAR(255),
      tanggal_simpan           VARCHAR(50),
      nomor_spd                VARCHAR(100),
      periode_spd              VARCHAR(100),
      nilai_spd                BIGINT DEFAULT 0,
      tahapan_spd              VARCHAR(100),
      nama_sub_tahapan_jadwal  VARCHAR(255),
      tahapan_apbd             VARCHAR(100),
      nomor_spp                VARCHAR(100),
      tanggal_spp              VARCHAR(50),
      nomor_spm                VARCHAR(100),
      tanggal_spm              VARCHAR(50),
      nomor_sp2d               VARCHAR(100),
      tanggal_sp2d             VARCHAR(50),
      tanggal_transfer         VARCHAR(50),
      nilai_sp2d               BIGINT DEFAULT 0,
      uploaded_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id)  REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (tahun_id) REFERENCES tahun_anggaran(id) ON DELETE CASCADE
    )
  `)
}
