export const name = '2026_01_01_000007_create_dokumen_realisasi_table'

export async function up(db) {
  await db.query(`
    CREATE TABLE IF NOT EXISTS dokumen_realisasi (
      id                       CHAR(36)  NOT NULL DEFAULT (UUID()),
      tahun_id                 CHAR(36)  NOT NULL,
      kode_skpd                VARCHAR(50),
      nama_skpd                VARCHAR(255),
      kode_sub_skpd            VARCHAR(50),
      nama_sub_skpd            VARCHAR(255),
      kode_fungsi              VARCHAR(20),
      nama_fungsi              VARCHAR(255),
      kode_sub_fungsi          VARCHAR(20),
      nama_sub_fungsi          VARCHAR(255),
      kode_urusan              VARCHAR(20),
      nama_urusan              VARCHAR(255),
      kode_bidang_urusan       VARCHAR(20),
      nama_bidang_urusan       VARCHAR(255),
      kode_program             VARCHAR(50),
      nama_program             VARCHAR(255),
      kode_kegiatan            VARCHAR(50),
      nama_kegiatan            VARCHAR(500),
      kode_sub_kegiatan        VARCHAR(50),
      nama_sub_kegiatan        VARCHAR(500),
      kode_rekening            VARCHAR(50),
      nama_rekening            VARCHAR(500),
      nomor_dokumen            VARCHAR(100),
      jenis_dokumen            VARCHAR(50),
      jenis_transaksi          VARCHAR(50),
      nomor_dpt                VARCHAR(100),
      tanggal_dokumen          DATETIME(6),
      keterangan_dokumen       TEXT,
      nilai_realisasi          DECIMAL(20,2) DEFAULT 0,
      nilai_setoran            DECIMAL(20,2) DEFAULT 0,
      nip_pegawai              VARCHAR(30),
      nama_pegawai             VARCHAR(255),
      tanggal_simpan           DATETIME(6),
      nomor_spd                VARCHAR(100),
      periode_spd              VARCHAR(100),
      nilai_spd                DECIMAL(20,2) DEFAULT 0,
      tahapan_spd              VARCHAR(100),
      nama_sub_tahapan_jadwal  VARCHAR(255),
      tahapan_apbd             VARCHAR(100),
      nomor_spp                VARCHAR(100),
      tanggal_spp              DATETIME(6),
      nomor_spm                VARCHAR(100),
      tanggal_spm              DATETIME(6),
      nomor_sp2d               VARCHAR(100),
      tanggal_sp2d             DATETIME(6),
      tanggal_transfer         DATETIME(6),
      nilai_sp2d               DECIMAL(20,2) DEFAULT 0,
      uploaded_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      FOREIGN KEY (tahun_id) REFERENCES tahun_anggaran(id) ON DELETE CASCADE
    )
  `)
}
